# Generated by Django 2.1.5 on 2019-02-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potatoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgritItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='IgritItems',
        ),
    ]
