# Generated by Django 2.1.5 on 2019-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potatoes', '0002_auto_20190209_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='igrititem',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
