# Generated by Django 2.1.5 on 2019-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potatoes', '0006_igrititem_is_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrititem',
            name='is_price',
            field=models.BooleanField(default=False),
        ),
    ]
