# Generated by Django 2.1.5 on 2019-02-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potatoes', '0007_auto_20190210_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igrititem',
            name='is_price',
        ),
    ]
