# Generated by Django 2.1.5 on 2019-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potatoes', '0009_igrititem_price_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrititem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
